server:
  port: 8080

cloud:
  aws:
    region:
      static: ${S3_REGION:ap-northeast-2}
    s3:
      bucket: ${S3_BUCKETNAME:artipcik-s3}

spring:
  profiles:
    active: local
    include:
      - secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:artipick}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

#jwt:
#  secretKey: ${JWT_SECRET_KEY}
#  access:
#    expiration: ${JWT_ACCESS_EXPIRATION}
#    header: ${JWT_ACCESS_HEADER}
#  refresh:
#    expiration: ${JWT_REFRESH_EXPIRATION}
#    header: ${JWT_REFRESH_HEADER}

# Springdoc (Swagger UI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    groups-order: ASC

logging:
  level:
    com.likelion.artipick: info
